---
name: Build and Deploy Dev
on:
  push:
    branches: [dev, multienv-wokflows]
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
jobs:
  build:
    permissions:
      packages: write
      id-token: write
      contents: write
    uses: ipfs-elastic-provider/ipfs-elastic-provider-indexer-lambda/.github/workflows/shared-build.yaml@multienv-wokflows
    with:
      docker_image_version_suffix_label: dev
    secrets:
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      aws_role_id: ${{ secrets.AWS_ROLE_ID }}
      aws_region: ${{ secrets.AWS_REGION }}
      aws_ecr_repository: ${{ secrets.AWS_ECR_REPOSITORY_DEV }}
  deploy:
    uses: ipfs-elastic-provider/ipfs-elastic-provider-indexer-lambda/.github/workflows/shared-deploy.yaml@multienv-wokflows
    permissions:
      id-token: write
      contents: write
    needs: build
    with:
      deploy_to_environment: dev
      lambda: dev-ep-indexer
      docker_image_version: ${{ needs.build.outputs.build_date }}-dev
    secrets:
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      aws_role_id: ${{ secrets.AWS_ROLE_ID }}
      aws_region: ${{ secrets.AWS_REGION }}
      aws_ecr_repository: ${{ secrets.AWS_ECR_REPOSITORY_DEV }}
