---
name: Build and Deploy Dev
on:
  push:
    branches: [dev, multienv-wokflows]
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
jobs:
  build:
    permissions:
      packages: write
    uses: ipfs-elastic-provider/ipfs-elastic-provider-indexer-lambda/.github/workflows/shared-build.yaml@dev
    with:
      docker_image_version_suffix_label: dev