---
name: Build And Deploy
on:
  push:
    branches: [main, multienv-wokflows] # TODO: Just main after integrating with deploy flow
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
jobs: # We need two separate builds as each is going to a different ECR repo
  build-staging:
    permissions:
      packages: write
      id-token: write
    uses: ipfs-elastic-provider/ipfs-elastic-provider-indexer-lambda/.github/workflows/shared-build.yaml@multienv-wokflows
    secrets:
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_region: ${{ secrets.AWS_REGION }}
      aws_ecr_repository: ${{ secrets.AWS_ECR_REPOSITORY_STAGING }}
  build-prod:
    permissions:
      packages: write
      id-token: write
    uses: ipfs-elastic-provider/ipfs-elastic-provider-indexer-lambda/.github/workflows/shared-build.yaml@multienv-wokflows
    secrets:
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_region: ${{ secrets.AWS_REGION }}
      aws_ecr_repository: ${{ secrets.AWS_ECR_REPOSITORY }}
  deploy-to-staging:
    uses: ipfs-elastic-provider/ipfs-elastic-provider-indexer-lambda/.github/workflows/shared-deploy.yaml@multienv-wokflows
    permissions:
      id-token: write
    needs: build-staging
    with:
      deploy_to_environment: staging
      lambda: staging-ep-indexer
      docker_image_version: ${{ needs.build-staging.outputs.build_date }}
    secrets:
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      aws_role_id: ${{ secrets.AWS_ROLE_ID }}
      aws_region: ${{ secrets.AWS_REGION }}
      aws_ecr_repository: ${{ secrets.AWS_ECR_REPOSITORY_STAGING }}
  deploy-to-prod:
    uses: ipfs-elastic-provider/ipfs-elastic-provider-indexer-lambda/.github/workflows/shared-deploy.yaml@multienv-wokflows
    permissions:
      id-token: write
    needs: build-prod
    with:
      deploy_to_environment: prod
      lambda: indexer
      docker_image_version: ${{ needs.build-prod.outputs.build_date }}
    secrets:
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      aws_role_id: ${{ secrets.AWS_ROLE_ID }}
      aws_region: ${{ secrets.AWS_REGION }}
      aws_ecr_repository: ${{ secrets.AWS_ECR_REPOSITORY }}
