name: PR Build
on:
  pull_request:
    branches:
      - main
      - dev
jobs:
  build:
    permissions:
      packages: write
    uses: ipfs-elastic-provider/ipfs-elastic-provider-indexer-lambda/.github/workflows/shared-build.yaml@pr-workflow
    with:
      docker_push: false
