---
name: 'Shared CD flow'
on:
  workflow_call:
    inputs:
      lambda:
        required: true
        type: string
        description: 'Lambda Name'
      docker_image_version:
        required: false
        type: string
        default: latest
        description: Used as version for ECR Docker image
    secrets:
      aws_account_id:
        required: true
      aws_access_key_id:
        required: true
        description: AWS Credentials
      aws_secret_access_key:
        required: true
        description: AWS Credentials
      aws_region:
        required: true
        description: AWS ECR Region
      aws_ecr_repository:
        required: true
        description: AWS ECR Repository

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js Current
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Prepare deployment
        run: |
          echo DOCKER_IMAGE_VERSION= ${{ inputs.docker_image_version }} >> $GITHUB_ENV
          echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
          echo PACKAGE_VERSION=$(cat package.json | jq -r '.version') >> $GITHUB_ENV
          echo BUILD_DATE=$(date +%Y%m%d.%H%M) >> $GITHUB_ENV
          echo LAMBDA=${{ inputs.lambda }} >> $GITHUB_ENV
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy Lambda
        run: |
          npm run deploy
        env:
          LAMBDA: ${{ inputs.lambda }}
          AWS_REGION: ${{ secrets.aws_region }}
          AWS_ACCOUNT_ID: ${{ secrets.aws_account_id }}
          AWS_ECR_REPOSITORY: ${{ secrets.aws_ecr_repository }}
